services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./config/.env/env.dev
    depends_on:
      - db
  db:
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/db/database-env

volumes:
  postgres_data:
